### ISSUE TITLE
Change skills to images

### ISSUE THREAD

**Issue by p-s-vishnu** [p-s-vishnu/p-s-vishnu.github.io#1]
Make this better in the next release by switching to icons

![image](https://user-images.githubusercontent.com/14847870/129508384-578a4700-489c-47b6-9faa-0b05590bd4da.png)

**Comment by iathul** [comment]
@p-s-vishnu I can work on this

**Comment by p-s-vishnu** [comment]
> @p-s-vishnu I can work on this

That will be excellent Athul, assigning it to you.

**Comment by iathul** [comment]
@p-s-vishnu Added the changes
